name: 'Annis & Zellers Pllc'
favicon: null
layout_spectrum: 0.7441127251368016
typography_spectrum: 0.43305327952839434
title: '" Estate Planning, Business Law, Tax Advice ... From A to Z."'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.9375
  lightness: 0.2875897230114788
  saturation: 0.3846033315639943
  rhythmicContrast: 0.3770701864268631
purpose: []
